### ISSUE TITLE
v2.93版本中101行报错AttributeError，另附一个临时解决方案

### ISSUE THREAD

**Issue by SSoyca** [gfriends/gfriends-inputer#36]
在2.93版本遇到了报错，运行日志如下：
```
Gfriends Inputer v2.93
https://git.io/gfriends

[HK]中国香港 已连通局部代理 女友仓库经由代理连接

按任意键开始...
√ 连接 Emby / Jellyfin 服务器成功
   演职人员：5015人

Traceback (most recent call last):
  File "/Users/zhanchangyou/PycharmProjects/gfriends-inputer/Gfriends Inputer.py", line 538, in <module>
    gfriends_map = get_gfriends_map(repository_url)
  File "/Users/zhanchangyou/PycharmProjects/gfriends-inputer/Gfriends Inputer.py", line 101, in get_gfriends_map
    for k, v in map_json[first][second].items():
AttributeError: 'int' object has no attribute 'items'

× 未知错误，在配置文件中开启 Debug 可获得错误详情。
```
把项目拉到本地看了一下发现可能是因为[主仓库的json](https://raw.githubusercontent.com/gfriends/gfriends/master/Filetree.json)用了新的结构，但是又没有更新这个处理循环，所以在处理的时候会遇到`map_json[first][second]`的值为int的情况，然后就会抛出AttributeError，下面是报错前的调试信息：
<img width="919" alt="image" src="https://user-images.githubusercontent.com/13702954/179254473-a0dd181c-e471-48f1-8a89-113e139fc015.png">

没有仔细看整个程序的具体流程，所以也就没有提requests，这里给遇到同样情况的哥们提供一个简单粗暴的解决方案，仅供临时规避问题使用，在101行的`for k, v in map_json[first][second].items():`之前，插入一个类型检查语句，专门检查`map_json[first][second]`的类型，判断如果类型为int则直接break循环，修改完之后差不多是这样（注意缩进）：
```python
    for first in first_lvls:
        second_lvls = map_json[first].keys()
        for second in second_lvls:  # 100行
            if type(map_json[first][second]) is int:  # 加了这一句判断类型
                break  # 当循环到int的时候直接break
            for k, v in map_json[first][second].items():  # 原101行
                secondstr = re.sub(".*-", "", second)
                if not secondstr in Black_List:
                    output[k[:-4]] = gfriends_template.format(first, second, v)
    print('√ 连接 Gfriends 女友头像仓库成功')
```
以上修复方法我已经实践过，一切运行正常，头像也能正常更新，算是xinxin大佬正式修复前的临时解决方案吧，仅供各位参考。附一个我的运行结果：
```
Gfriends Inputer v2.93
https://git.io/gfriends

已配置局部代理 http://127.0.0.1:7890，但似乎无法连通，请检查其格式和可用性

按任意键开始...
√ 连接 Emby / Jellyfin 服务器成功
   演职人员：5015人

√ 连接 Gfriends 女友头像仓库成功
   库存头像：151211枚

√ 引擎初始化成功

>> 下载头像...
[========================================] 160/160 [100%] in 0:01:18 (2.04/s)
√ 下载完成

>> 尺寸优化...
[========================================] 160/160 [100%] in 3.4s (47.16/s)
√ 优化完成

>> 导入头像...
[========================================] 160/160 [100%] in 54.4s (2.94/s)
√ 导入完成

Emby / Jellyfin 演职人员共 5015 人，其中 1508 人之前已有头像
本次导入 160 人，还有 4855 人没有头像
```

**Comment by xinxin8816** [comment]
感谢提醒，[v2.94](https://github.com/gfriends/gfriends-inputer/releases/tag/v2.94) 及后续版本适配新仓库。

**Gfriends Inputer v2.93 及更早的版本不兼容新仓库，如果您有旧版使用需求，则需要手动指定[旧版仓库地址](https://github.com/gfriends/gfriends/tags)** (将不会收到头像更新)
