### ISSUE TITLE
v3.02: ImportError: libGL.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by djomiyoupak** [gfriends/gfriends-inputer#48]
系统版本: Unraid 6.10.3
软件版本: Gfriends Inputer v3.02 - Gfriends-Inputer-Linux.zip

错误信息:
```
Traceback (most recent call last):
  File "Gfriends Inputer.py", line 771, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "Lib/cv2dnn.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "cv2/__init__.py", line 5, in <module>
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[17341] Failed to execute script 'Gfriends Inputer' due to unhandled exception!
```

**Comment by xinxin8816** [comment]
系统缺少组件，请换用其他系统远程连接
后续会改进逻辑来跳过这种情况

**Comment by xinxin8816** [comment]
[v3.03](https://github.com/gfriends/gfriends-inputer/releases) 改善了 OpenCV 初始化的失败的处理逻辑
