### ISSUE TITLE
NameError: name 'cv2' is not defined

### ISSUE THREAD

**Issue by ly012** [gfriends/gfriends-inputer#53]
C:\Users\Administrator\Desktop\Gfriends-Inputer-Windows>"Gfriends Inputer.exe"
Traceback (most recent call last):
  File "Lib\cv2dnn.py", line 7, in <module>
  File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI48002\cv2\__init__.py", line 5,
 in <module>
    from .cv2 import *
ImportError: DLL load failed while importing cv2: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Gfriends Inputer.py", line 772, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "Lib\cv2dnn.py", line 25, in <module>
NameError: name 'cv2' is not defined
[4412] Failed to execute script 'Gfriends Inputer' due to unhandled exception!

系统是Windows2012，下载的是最新的3.03

debian11上运行源码版也不行。

Traceback (most recent call last):
  File "/opt/gfriends-inputer/Lib/cv2dnn.py", line 7, in <module>
    import cv2
  File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/gfriends-inputer/./Gfriends Inputer.py", line 772, in <module>
    from Lib.cv2dnn import find_faces
  File "/opt/gfriends-inputer/Lib/cv2dnn.py", line 25, in <module>
    except cv2.error:
NameError: name 'cv2' is not defined

**Comment by xinxin8816** [comment]
系统不支持 本地AI识别  ，请将配置文件中的尺寸优化功能调整为 本地AI识别 以外的选项

ly012 ***@***.***> 于2022年9月22日周四 08:35写道：
