### ISSUE TITLE
显示下列信息后出错自动退出！！

### ISSUE THREAD

**Issue by xbcui1975** [gfriends/gfriends-inputer#59]
Traceback (most recent call last):
File "Gfriends Inputer.py", line 676, in check_update
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Gfriends Inputer.py", line 823, in
File "Gfriends Inputer.py", line 740, in check_update
TypeError: catching classes that do not inherit from BaseException is not allowed
[15732] Failed to execute script 'Gfriends Inputer' due to unhandled exception!

**Comment by xinxin8816** [comment]
检查代理确保程序可以连接 GitHub
或者运行时增加参数 `--skip-update`

**Comment by xbcui1975** [comment]
问题已解决，是代理出问题了！
