### ISSUE TITLE
启动后检查更新然后报错自动退出

### ISSUE THREAD

**Issue by Rebuilding127** [gfriends/gfriends-inputer#71]
启动时会检查更新，然后报错，等待几秒后自动退出。
根据源码来看，至少也该提示更新失败或网络问题，然后跳过继续运行，但没有。
而且我检查过，网络也没问题，代理也开着。

报错日志如下：
```log
Traceback (most recent call last):
  File "Gfriends Inputer.py", line 676, in check_update
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Gfriends Inputer.py", line 823, in <module>
  File "Gfriends Inputer.py", line 740, in check_update
TypeError: catching classes that do not inherit from BaseException is not allowed
[10892] Failed to execute script 'Gfriends Inputer' due to unhandled exception!
```

**Comment by Rebuilding127** [comment]
额，过了几小时后重新试了一下又可以用了，问题是我啥也没干，费解。。。

**Comment by DoubleD-Liangzai** [comment]
> 额，过了几小时后重新试了一下又可以用了，问题是我啥也没干，费解。。。

需要翻墙

**Comment by Rebuilding127** [comment]
> > 额，过了几小时后重新试了一下又可以用了，问题是我啥也没干，费解。。。
> 
> 需要翻墙

VPN一直开着的，当时还特意打开网页确认过，所以才费解
